apiVersion: v1
kind: Service
metadata:
  name: {{ include "apex.fullname" . }}-api
  labels:
    {{- include "apex.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "apex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
